# Basic docker-compose file
version: "3.9"
services:
  # Service registration and discovery
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command:
      [
        "etcd",
        "--advertise-client-urls",
        "http://etcd:2379",
        "--listen-client-urls",
        "http://0.0.0.0:2379",
      ]
    ports:
      - "2379:2379"
  http-server:
    image: czsheng/cloudwego-api-gateway
    volumes:
      - ./idl/:/etc/idl
      - gateway-logs:/logs
    environment:
      - ETCD_ADDR=http://etcd:2379
      - LOG_PATH=/logs/output.log
    ports:
      - "8080:8080"
    depends_on:
      - etcd
  rpc-server:
    build: .
    environment:
      - ETCD_ADDR=http://etcd:2379
      - LOG_PATH=/logs/rpc-server.log
      - CONTAINER=rpc-server
    volumes:
      - gateway-logs:/logs
    depends_on:
      - etcd
volumes:
  gateway-logs:
