version: "3.9"
services:
  # Service registration and discovery
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command:
      [
        "etcd",
        "--advertise-client-urls",
        "http://etcd:2379",
        "--listen-client-urls",
        "http://0.0.0.0:2379",
      ]
    ports:
      - "2379:2379"
  http-server:
    image: czsheng/cloudwego-api-gateway
    volumes:
      - ../../tests/hello/idl/:/etc/idl
    environment:
      - ETCD_ADDR=http://etcd:2379
      - LOGFILE=/logs/http-server.log
    ports:
      - "8080:8080"
    depends_on:
      - etcd
  rpc-server:
    build: rpc-server
    environment:
      - ETCD_URL=http://etcd:2379
      - CONTAINER=rpc-server
      - LOGFILE=/logs/rpc-server.log
    volumes:
      - gateway-logs:/logs
    ports:
      - "8888:8888"
    depends_on:
      - etcd
volumes:
  gateway-logs:
