// Code generated by hertz generator.
package main

import (
	"context"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(
		server.WithHostPorts("127.0.0.1:8080"),
	)

	h.Use(func(c context.Context, ctx *app.RequestContext) {
		// log.Printf("Sample middleware pre-handler")
		ctx.Next(c)
		log.Printf("Request status code: %d", ctx.Response.StatusCode())
	})

	register(h)
	h.Spin()
}
